"$schema" = 'https://starship.rs/config-schema.json'

add_newline = false
palette = "ao"
right_format = "$time"
format = """
$username\
$hostname\
$directory\
$git_branch\
$git_state\
$git_status\
$line_break\
$python\
$cmd_duration\
$character"""

[line_break]
disabled = true

[directory]
style = "bold fg:ao_cwd"
read_only_style = "fg:ao_red"
truncation_length = 7
truncation_symbol = "…/"
truncate_to_repo = false

[character]
success_symbol = "[❯](bold fg:ao_purple)"
error_symbol = "[❯](bold fg:ao_red)"
vimcmd_symbol = "[❮](bold fg:ao_green)"

[git_branch]
symbol = " "
format = "[|](fg:ao_muted)[ $symbol$branch]($style)"
style = "fg:ao_yellow"

[git_status]
format = "[[(*$conflicted$untracked$modified$staged$renamed$deleted)](fg:ao_purple) ($ahead_behind$stashed )]($style)"
style = "fg:ao_blue"
conflicted = "​"
untracked = "​"
modified = "​"
staged = "​"
renamed = "​"
deleted = "​"
stashed = "≡"

[git_state]
format = '\([$state( $progress_current/$progress_total)]($style)\)'
style = "fg:ao_yellow"

[cmd_duration]
min_time = 10000
format = "[|](fg:ao_muted)[ $duration ]($style)"
style = "fg:ao_yellow"

[python]
symbol = " "
format = "[|](fg:ao_muted)[${pyenv_prefix} $symbol(${version} )(($virtualenv) )]($style)"
style = "fg:ao_green"
detect_extensions = []
detect_files = []

[username]
style_user = "fg:ao_yellow"
style_root = "bold fg:ao_red"

[hostname]
style = "fg:ao_muted"

[time]
disabled = false
time_format = "%T"
format = '[$time ]($style)'
style = "dimmed fg:ao_yellow"

[palettes.ao]
ao_bg = "#080d15"
ao_surface = "#0d1526"
ao_overlay = "#2c5484"
ao_muted = "#838a97"
ao_fg = "#f3f4f6"
ao_cwd = "#6eb0ff"
ao_blue = "#45b1e8"
ao_green = "#81be83"
ao_yellow = "#ffba00"
ao_orange = "#ff9000"
ao_red = "#fa7970"
ao_purple = "#d2a8ff"
